# Generated by Django 5.0.4 on 2024-05-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='test1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='note',
            name='test2',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='note',
            name='test3',
            field=models.CharField(max_length=20),
        ),
    ]
